config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#show"
  get 'us', to: 'properties#us'
  get 'contact', to: 'properties#contact'
  resources :users do
    get :switch, on: :member
  end
  resources :properties do
    get :search, on: :collection
    get :mine, on: :collection
    get :suggestions, on: :collection
    get :suggest, on: :collection
    put :set_state, on: :member
    post :interest, on: :member
    resources :property_assets, controller: 'properties/property_assets' do
      delete :delete_image, on: :member
      delete :delete_video, on: :member
    end
    resources :properties_users, controller: 'properties/properties_users' do
      put :seen, on: :member
      put :unseen, on: :member
    end
  end

  resources :commercial_lands do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :residential_plots do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :commercial_buildings do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :residential_houses do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :villas do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :rental_houses do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :rental_offices do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :rental_shops do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :messages
end

app/models/rental_office.rb
class RentalOffice < House
  def summary
    "#{area} square feet office for rent at #{place}"
  end

  def set_suggestion
    self.suggestion = "office for rent at #{place}"
  end

  def common_tags
    ' kerala office rent rental rented '
  end
end

app/controllers/rental_offices_controller.rb
class RentalOfficesController < PropertiesController
end

app/views/rental_offices/_filter.haml
.filter-container
  .h3
    Search Office Spaces for rent
  .filter
    = form_with(url: '/index', method: 'get', class: 'filter-form', data: {url: rental_offices_path}) do
      .place-filter
        = label_tag 'Nearby Place'
        .clearfix
        = text_field_tag 'place', session[:place], class: 'place-filter-field office-place-filter-field'
        .suggestions.places.d-none
      .budget-filter
        = label_tag 'Budget'
        .clearfix
        = text_field_tag 'price1', nil, class: 'filter-field office-filter-field'
        to
        = text_field_tag 'price2', nil, class: 'filter-field pull-right office-filter-field'
        .clearfix
      .budget-filter
        = label_tag 'Area in square feets'
        .clearfix
        = text_field_tag 'area1', nil, class: 'filter-field office-filter-field'
        to
        = text_field_tag 'area2', nil, class: 'filter-field pull-right office-filter-field'
        .clearfix
            
      = hidden_field_tag 'filtering', 'true'
      = hidden_field_tag  'state', [params[:state], 'approved'].find(&:present?)

app/views/rental_offices/form.haml
.property-form-container
  %h2
    = "#{action_name.camelize} #{@klass_underscore.split('_').last.camelize}"
  = simple_form_for(@property) do |f|
    = f.input :place, label: 'Place', input_html: {class: 'place-filter-field'}
    .suggestions.places.d-none
    = f.input :expected_price
    = f.input :landmark
    = f.input :area, label: 'Area in square feets'
    = f.input :img1, label: "Photo (required)", required: true
    - if current_user.admin?
      %h3
        Admin section
      = f.input :district, collection: [["Thiruvananthapuram", "Thiruvananthapuram"], ["Kollam", "Kollam"], ["Alappuzha", "Alappuzha"], ["Pathanamthitta", "Pathanamthitta"], ["Kottayam", "Kottayam"], ["Idukki", "Idukki"], ["Ernakulam", "Ernakulam"], ["Thrissur", "Thrissur"], ["Palakkad", "Palakkad"], ["Malappuram", "Malappuram"], ["Kozhikode", "Kozhikode"], ["Wayanadu", "Wayanadu"], ["Kannur", "Kannur"], ["Kasaragod", "Kasaragod"]]
      = f.input :visible_caption
      = f.input :tags
    = f.submit 'Submit'
  = link_to 'cancel', rental_offices_path