config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#show"
  get 'us', to: 'properties#us'
  get 'contact', to: 'properties#contact'
  resources :users do
    get :switch, on: :member
  end
  resources :properties do
    get :search, on: :collection
    get :mine, on: :collection
    get :suggestions, on: :collection
    get :suggest, on: :collection
    put :set_state, on: :member
    post :interest, on: :member
    resources :property_assets, controller: 'properties/property_assets' do
      delete :delete_image, on: :member
      delete :delete_video, on: :member
    end
    resources :properties_users, controller: 'properties/properties_users' do
      put :seen, on: :member
      put :unseen, on: :member
    end
  end

  resources :commercial_lands do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :residential_plots do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :commercial_buildings do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :residential_houses do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :villas do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :rental_houses do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :rental_offices do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :rental_shops do
    put :set_state, on: :member
    post :interest, on: :member
    get :suggest, on: :collection
    get :interests, on: :collection 
  end

  resources :messages
end

app/models/residential_plot.rb
class ResidentialPlot < Land
  def summary
    acre1 = acre.to_i > 0 ? "#{acre} acre" : nil
    cent1 = cent.to_i > 0 ? "#{cent} cent" : nil
    [acre1, cent1, "plot for sale at #{place}"].select(&:present?).join(' ')
  end

  def set_suggestion
    self.suggestion = "plot at #{place}"
  end

  def common_tags
    'plot plot place for sale '
  end
end

app/controllers/residential_plots_controller.rb
class ResidentialPlotsController < PropertiesController
end

app/views/residential_plots/_filter.haml
.filter-container
  .h3
    Search Ploats for sale
  .filter
    = form_with(url: '/index', method: 'get', class: 'filter-form', data: {url: residential_plots_path}) do
      .place-filter
        = label_tag 'Nearby Place'
        .clearfix
        = text_field_tag 'place', session[:place], class: 'property-place-filter-field place-filter-field'
        .suggestions.places.d-none
      .budget-filter
        = label_tag 'Budget'
        .clearfix
        = text_field_tag 'price1', nil, class: 'filter-field property-filter-field'
        to
        = text_field_tag 'price2', nil, class: 'filter-field property-filter-field pull-right'
        .clearfix
      .land-mass-filter
        = label_tag 'acres'
        = text_field_tag 'acre1', nil, class: 'filter-field property-filter-field', placeholder: 'acres'
      .land-mass-filter.pull-right
        = label_tag 'cents', nil, class: 'pull-right'
        = text_field_tag 'cent1', nil, class: 'filter-field property-filter-field pull-right', placeholder: 'cents'
      .to
        to
      .land-mass-filter
        = label_tag 'acres'
        = text_field_tag 'acre2', nil, class: 'filter-field property-filter-field', placeholder: 'acres'
      
      .land-mass-filter.pull-right
        = label_tag 'cents', nil, class: 'pull-right'
        = text_field_tag 'cent2', nil, class: 'filter-field property-filter-field pull-right', placeholder: 'cents'      
      
      = hidden_field_tag 'filtering', 'true'
      = hidden_field_tag  'state', [params[:state], 'approved'].find(&:present?)

app/views/residential_plots/form.haml
.property-form-container
  %h2
    = "#{action_name.camelize} #{@klass_underscore.split('_').last.camelize}"
  = simple_form_for(@property) do |f|
    = f.input :place, label: 'Place', input_html: {class: 'property-place-filter-field place-filter-field'}
    .suggestions.places.d-none
    = f.input :acre
    = f.input :cent
    = f.input :expected_price
    = f.input :landmark
    = f.input :img1, label: "photo (required)", required: true
    - if current_user.admin?
      %h3
        Admin section
      = f.input :district, collection: [["Thiruvananthapuram", "Thiruvananthapuram"], ["Kollam", "Kollam"], ["Alappuzha", "Alappuzha"], ["Pathanamthitta", "Pathanamthitta"], ["Kottayam", "Kottayam"], ["Idukki", "Idukki"], ["Ernakulam", "Ernakulam"], ["Thrissur", "Thrissur"], ["Palakkad", "Palakkad"], ["Malappuram", "Malappuram"], ["Kozhikode", "Kozhikode"], ["Wayanadu", "Wayanadu"], ["Kannur", "Kannur"], ["Kasaragod", "Kasaragod"]]
      = f.input :visible_caption
      = f.input :tags
    = f.submit 'Submit'
  = link_to 'cancel', residential_plots_path